version: "3"
services:
  dev-back-blue:
    container_name: tcp-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: "prod"
    ports:
      - "8091:8091"
    networks:
      - br_app

networks:
  br_app:
    external: true
