version: "3"
services:
  dev-back-blue:
    container_name: tcp-server
    build:
      context: src
      dockerfile: Dockerfile
      args:
        PROFILE: "default"
    ports:
      - "8050:8050"
      - "9090:9090"
    networks:
      - br_log
      - br_app

networks:
  br_log:
    external: true
  br_app:
    external: true
