spring:
#  datasource:
#    username: root
#    password: 1234
  influxdb:
    username: semse
    password: semse201!
    token:
      xmAjohkqSXI4MCihz8U4R-KbqQNYYDvW93Xrzcl8C6OEAZSWaqc5WWUI3s2H9JVZrrsl7SkD1vm9xZ0eRPz_vQ==
#      EBOQzZOcOV8XTh3z_B7ZW1k8hLw54-VN10YlhrCbnejZFPuUuFGvllz1RDRt6zdHaL-J7EYae5RoHonvyBQpPg==