server:
  port: 8091

spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/data?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=Asia/Seoul
  websocket:
    connection-timeout: 5000000
    max-binary-message-buffer-size: 5000000
    handshake-timeout: 300000
  influxdb:
    url: http://k8e201.p.ssafy.io:8086

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:


logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: debug