server:
  tomcat:
    max-threads: 500
  servlet:
    context-path: /api

spring:
  profiles:
    active: local, secret
  influxdb:
    connectionTimeoutMs: 5000
#  websocket:
#    connection-timeout: 5000000
#    max-binary-message-buffer-size: 50000
#    handshake-timeout: 300000
  jpa:
    properties:
      hibernate:
        jdbc.time_zone: Asia/Seoul

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

management:
  endpoints:
    web:
      exposure:
        include: "*"  # *으로 표기하면 전체
