spring:
  profiles:
    active: local, secret

  influxdb:
    url: http://k8e2011.p.ssafy.io:8086
    #    url: http://localhost:8086


  jpa:
    properties:
      hibernate:
        jdbc.time_zone: Asia/Seoul

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB